//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sdl.Community.MtEnhancedProvider {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MtPluginUpdateAvailableDialogResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MtPluginUpdateAvailableDialogResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sdl.Community.MtEnhancedProvider.MtPluginUpdateAvailableDialogResources", typeof(MtPluginUpdateAvailableDialogResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind me later.
        /// </summary>
        internal static string btn_later_Text {
            get {
                return ResourceManager.GetString("btn_later_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip this version.
        /// </summary>
        internal static string btn_skip_Text {
            get {
                return ResourceManager.GetString("btn_skip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download update.
        /// </summary>
        internal static string btn_update_Text {
            get {
                return ResourceManager.GetString("btn_update_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT Enhanced Update Available.
        /// </summary>
        internal static string form_Text {
            get {
                return ResourceManager.GetString("form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Version:.
        /// </summary>
        internal static string lbl_current_label_Text {
            get {
                return ResourceManager.GetString("lbl_current_label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Version:.
        /// </summary>
        internal static string lbl_latestVersion_label_Text {
            get {
                return ResourceManager.GetString("lbl_latestVersion_label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new update for MT Enhanced Plugin is avaialable..
        /// </summary>
        internal static string lbl_message_Text {
            get {
                return ResourceManager.GetString("lbl_message_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Notes:.
        /// </summary>
        internal static string lbl_releaseNotes_Text {
            get {
                return ResourceManager.GetString("lbl_releaseNotes_Text", resourceCulture);
            }
        }
    }
}
